### ISSUE TITLE
How

### ISSUE THREAD

**Issue by wuxiaopei0509** [philippbayer/orthomclToVenn#1]
Hi,I used https://github.com/apetkau/orthomcl-pipeline and does not get singletons that are not contained in any clusters.How could I get the singletons ?
Can you share you methods?
Thank you!

**Comment by philippbayer** [comment]
hi! orthoMCL comes with a script to get the singletons: `orthomclSingletons`. It is in the `bin` folder of the orthoMCL download at https://orthomcl.org/common/downloads/software/v2.0/orthomclSoftware-v2.0.9.tar.gz
